### ISSUE TITLE
Very poor accuracy for flare location

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#17]
The inaccuracy blue circle is 3 miles wide.

Can we tighten this up?

**Comment by jcampbell05** [comment]
@alexsup the blue circle is based on your location obtained directly by Apple Maps, we do not control the level of accuracy in this case since they are using their own internal tracker.

Therefore the device must be somewhere the GPS is having difficulties obtaining an accurate signal (i.e. in the basement of a super cool tech shared office space).
