### ISSUE TITLE
When I show after being dark, the app tells me I have no friends

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#56]
Given I am on the radar
When I click on hide
And then on show
Then I have a screen that says I have no friends.

**Comment by jcampbell05** [comment]
@alexsup  Should be fixed in https://github.com/Supmenow/Sup-iOS/pull/980 

We probably need to split out the view model for the radar so we have one for the data of the Radar and another which handle the visibility of the user (and maybe location too, although that could become a background service.)
